apiVersion: v1
kind: Service
metadata:
  name: generator-service
spec:
  type: LoadBalancer
  selector:
    app: generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
